import {test} from 'node:test';import assert from 'node:assert/strict';import {createApp} from './server.mjs';import {createHash} from 'node:crypto';
async function setup(t,fetcher){const server=createApp({clientId:'test-client',clientSecret:'test-secret',appUrl:'http://localhost:4173',fetcher});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const root=`http://127.0.0.1:${server.address().port}`;return (path,opts={})=>fetch(root+path,{redirect:'manual',...opts});}
test('OAuth state, PKCE, private server tokens, paged sync, origin guard, logout',async t=>{
 let challenge;const calls=[];
 const request=await setup(t,async(url,options)=>{calls.push(url);if(url.endsWith('/oauth2/token')){assert.equal(createHash('sha256').update(options.body.get('code_verifier')).digest('base64url'),challenge);assert.equal(options.body.get('redirect_uri'),'http://localhost:4173/auth/callback');return Response.json({access_token:'private-token',expires_in:7200});}assert.equal(options.headers.Authorization,'Bearer private-token');if(url.endsWith('/users/me'))return Response.json({data:{id:'123',username:'tester'}});const parsed=new URL(url);assert.equal(parsed.searchParams.get('pagination_token'),'next-page');return Response.json({data:[{id:'789',text:'Saved text',author_id:'42'}],includes:{users:[{id:'42',username:'writer'}]},meta:{next_token:'page-two'}});});
 const login=await request('/auth/login');const auth=new URL(login.headers.get('location'));assert.equal(auth.origin,'https://x.com');assert.equal(auth.searchParams.get('code_challenge_method'),'S256');assert.equal(auth.searchParams.get('scope'),'tweet.read users.read like.read bookmark.read');challenge=auth.searchParams.get('code_challenge');const oauthCookie=login.headers.get('set-cookie').split(';')[0];
 const callback=await request(`/auth/callback?code=code&state=${auth.searchParams.get('state')}`,{headers:{cookie:oauthCookie}});assert.equal(callback.headers.get('location'),'/?x_connected=1');const cookie=callback.headers.getSetCookie().find(x=>x.startsWith('savedesk_session=')).split(';')[0];assert.ok(!cookie.includes('private-token'));
 const session=await request('/api/session',{headers:{cookie}});assert.deepEqual((await session.json()).user,{id:'123',username:'tester'});
 assert.equal((await request('/api/sync?source=like',{method:'POST',headers:{cookie,origin:'https://evil.example'}})).status,403);
 for(const source of ['like','bookmark']){const response=await request(`/api/sync?source=${source}&cursor=next-page`,{method:'POST',headers:{cookie,origin:'http://localhost:4173'}});const body=await response.json();assert.equal(body.items[0].author,'writer');assert.equal(body.items[0].source,source);assert.equal(body.next,'page-two');}
 const replay=await request(`/auth/callback?code=code&state=${auth.searchParams.get('state')}`,{headers:{cookie:oauthCookie}});assert.equal(replay.headers.get('location'),'/?x_error=state');
 await request('/api/disconnect',{method:'POST',headers:{cookie,origin:'http://localhost:4173'}});assert.equal((await (await request('/api/session',{headers:{cookie}})).json()).connected,false);assert.equal(calls.length,4);
});
test('invalid callbacks never exchange tokens and secrets are not served',async t=>{const request=await setup(t,()=>{throw Error('must not call X');});assert.equal((await request('/auth/callback?code=x&state=wrong')).headers.get('location'),'/?x_error=state');assert.equal((await request('/server.mjs')).status,404);assert.equal((await request('/.env')).status,404);assert.equal((await request('/api/sync?source=like',{method:'POST',headers:{origin:'http://localhost:4173'}})).status,401);});
